<?php
function multistep_menu() {
  $items['multistep'] = array(
    'title' => 'multistep',
    'page callback' => 'multistep_form',
    //'page arguments' => array('multistep_form'),
    'access callback' => TRUE,
    'menu_name' => 'navigation',
  );
  return $items;
}
/**
 * Implement hook_form().
 */
function multistep_form(&$node, $form_state) {
  // Initial step: display title and body fields.
  if (!isset($form_state['storage']['step'])) {
    $form['title'] = array(
      '#title' => t('Title'),
      '#type' => 'textfield',
      '#required' => TRUE,
      '#default_value' => isset($form_state['storage']['title']) ? $form_state['storage']['title'] : $node->title,
    );
    $form['body_field'] = node_body_field($node, t('Body'), 1);
  }
  // Second step: display
  else {
    $form['additional_info'] = array(
      '#title' => t('Additional information'),
      '#type' => 'textarea',
      '#required' => TRUE,
      '#default_value' => isset($form_state['storage']['additional_info']) ? $form_state['storage']['additional_info'] : $node->additional_info,
    );
  }

  return $form;
}

/**
 * Implement hook_form_alter().
 */
function multistep_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'multistep_node_form') {
    $node = $form['#node'];



    // Page 1, $form_state['storage']['step'] isn't set yet, so display first form.
    if (empty($form_state['storage']['step'])) {
      // Hide everything except title, body and button fields.
      $fields = array('title', 'body');
      multistep_make_node_multistep($form, $fields, 'multistep_step1_form_next_handler');
    }
  }
}

function multistep_make_node_multistep(&$form, $fields, $submit_handler) {
  // Hide all the elements we don't want.
  foreach (element_children($form) as $child) {
    if ($child != 'buttons' && !in_array($child, $fields) &&
        (empty($form[$child]['#type']) ||
         ($form[$child]['#type'] != 'hidden'
          && $form[$child]['#type'] != 'value'
          && $form[$child]['#type'] != 'token'))) {
      $form[$child]['#access'] = FALSE;
    }
  }

// Hide the submit button.
  $form['buttons']['submit']['#access'] = FALSE;

  // Change the 'preview' button to 'Next' and set the submit handler.
  $form['buttons']['preview'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
    '#weight' => 50,
    '#submit' => array($submit_handler),
  );
}

function multistep_step1_form_next_handler($form, &$form_state) {
  $form_state['storage']['step'] = 1;
}
