<?php

/**
 *
 */

/**
 * Implements hook_help().
 */
function newsletter_help($path, $arg) {
  switch ($path) {
    case "admin/help#newsletter":
      return '' . t("Adds the ability to send news and selection of news categories.") . '';
      break;

  }
}

/**
 * Implements hook_menu().
 */
function newsletter_menu() {
  $items['user/%user/subscriptions'] = [
    'title' => 'Subscriptions',
    'page callback' => 'newsletter_profile_form',
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'menu_name' => 'user-menu',
    'file' => 'user.pages.inc',
    'file path' => drupal_get_path('module', 'user'),
  ];
  $items['user/register/news_categories'] = [
    'title' => 'Subscriptions',
    'page callback' => 'newsletter_register_form',
    'access callback' => TRUE,
    'menu_name' => 'user-menu',
    'file' => 'user.pages.inc',
    'file path' => drupal_get_path('module', 'user'),
  ];
  return $items;
}

/**
 * Implements hook_form().
 */
function newsletter_profile_form() {
  module_load_include('inc', 'user', 'user.pages');
  global $user;
  $user = user_load($user->uid);
  $form = drupal_get_form('user_profile_form', $user, 'account', 'custom');
  return $form;
}

/**
 * Implements hook_form().
 */
function newsletter_register_form() {
  module_load_include('inc', 'user', 'user.pages');
  global $user;
  $user = user_load($user->uid);
  $form = drupal_get_form('user_register_form', $user, 'account', 'custom');
  return $form;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function newsletter_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form_state['build_info']['args'][2]) &&
    $form_state['build_info']['args'][2] = 'custom'
  ) {
    $form['picture']['#access'] = FALSE;
    $form['account']['#access'] = FALSE;
    $form['#after_build'][] = 'newsletter_timezone_hide';
  }
  else {
    $form['field_get_news']['#access'] = FALSE;
    $form['field_news_categories']['#access'] = FALSE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function newsletter_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form_state['build_info']['args'][2]) &&
    $form_state['build_info']['args'][2] = 'custom'
  ) {
    $form['picture']['#access'] = FALSE;
    $form['account']['#access'] = FALSE;
    $form['#after_build'][] = 'newsletter_timezone_hide';
    $form['field_get_news']['#access'] = FALSE;

    $form['account']['name']['#default_value'] = $_SESSION['account']['name'];
    $form['account']['mail']['#default_value'] = $_SESSION['account']['mail'];
    $form['field_get_news']['#default_value'] = $_SESSION['account']['news'];

    $form['actions']['back']['#type'] = 'submit';
    $form['actions']['back']['#value'] = "Back";
    $form['actions']['back']['#submit'][] = 'newsletter_form_user_register_form_back_submit';
  }
  else {
    $form['field_news_categories']['#access'] = FALSE;

    $form['actions']['next']['#type'] = 'submit';
    $form['actions']['next']['#value'] = "Next";
    $form['actions']['next']['#submit'][] = 'newsletter_form_user_register_form_next_submit';
    $form['actions']['next']['#states'] = [
      'visible' => [
        ':input[name="field_get_news"]' => ['checked' => TRUE],
      ],
    ];
    $form['actions']['submit']['#states'] = [
      'visible' => [
        ':input[name="field_get_news"]' => ['checked' => FALSE],
      ],
    ];

    if (!empty($_SESSION)) {
      $form['account']['name']['#value'] = $_SESSION['account']['name'];
      $form['account']['mail']['#value'] = $_SESSION['account']['mail'];
      $form['field_get_news']['#value'] = $_SESSION['account']['news'];
    }
  }
}

function newsletter_timezone_hide($form, &$form_state) {
  $form['timezone']['#access'] = FALSE;
  return $form;
}

/*
 * next button on first page of reg form
 */
function newsletter_form_user_register_form_next_submit($form, &$form_state) {
  $val = $form_state['values'];
  $_SESSION['account']['name'] = $val['name'];
  $_SESSION['account']['mail'] = $val['mail'];
  $_SESSION['account']['news'] = $val['field_get_news']['und'][0]['value'];
  $message = t('name = ' . $val['name'] . ' mail = ' . $val['mail']);
  drupal_set_message($message, 'status');
  $form_state['redirect'] = 'user/register/news_categories';
}

function newsletter_form_user_register_form_back_submit($form, &$form_state) {
  $form_state['redirect'] = 'user/register';
}
